# Generated by Django 5.1 on 2024-08-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blogs.blog_post'),
        ),
    ]
