# Generated by Django 5.1 on 2024-08-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blog_post', to='blogs.tag'),
        ),
    ]
