# Generated by Django 5.1 on 2024-08-23 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blogs.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blogs.category'),
            preserve_default=False,
        ),
    ]
