# Generated by Django 5.1 on 2024-08-28 10:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_alter_blog_post_tags_alter_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
